mice:
    - name: "Contour"
      accel: -0.9
     #stabilizeClick:
     #  button: 1
     #  factor: 2

    - name: "Evoluent"
      accel: -0.8

    - name: "Penclic"
      accel: -0.7
      buttonMap: 1 2 3 4 5
      accelProfile: 0 1

   #- name: "Kingsis Peripherals Evoluent VerticalMouse 4"
   #  decel: 3.5
   #  linear: true
   #  buttonMap: "1 9 3 4 5 6 7 6 9 7"
   #  controlAccel:
   #    button: 2 
   #    factor: 0.5 
