mice:
    - name: "Contour"
      decel: 4 

    - name: "Kingsis Peripherals Evoluent VerticalMouse 4"
      decel: 3.5
      linear: true
      buttonMap: "1 9 3 4 5 6 7 6 9 7"
      controlAccel:
        button: 2 
        factor: 0.5 
